require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "spec/fixtures/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/HashExcept:
  Enabled: false  # Requires ActiveSupport, which is not a dependency

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Exclude:
    - "lib/llm_classifier/classifier.rb"
    - "lib/llm_classifier/content_fetchers/web.rb"

Metrics/ParameterLists:
  Exclude:
    - "lib/llm_classifier/result.rb"

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5
